rosbag2_evaluation:
  ros__parameters:
    dds: ["rmw_cyclonedds_cpp"] # ["rmw_cyclonedds_cpp","rmw_fastrtps_cpp"]
    repeat: 1
    perf_test_parameters:
      topics: ["Array1k"] # you can set the below configurations
      rate: ["30"] 
      reliability: ["reliable"] # fixed
      durability: ["volatile"] # fixed
      number_of_publish: 100
    rosbag2_parameters:
      record:
        no_discovery: ["false"] #["true","false"]
        max_cache_size: ["0"] #["0","guide","default","209715200" ] #default=100mebibytes=104857600bytes,209715200
        storage_preset_profile: ["default"] #["default","resilient"] 
        qos:
          reliability: ["reliable"]
          durability: ["volatile"]
      play:
        read_ahead_queue_size: ["10485760"] #default=1000 [1MiB,10MiB,100MiB] = ["1048576","10485760","104857600"]
        rate: ["default"] #fixed
        qos:
          reliability: ["reliable"] # fixed
          durability: ["transient"] # fixed

#topics = [
# "Array1k", "Array4k", "Array16k", "Array32k", "Array64k", "Array256k","Array1m", "Array2m", 
# "Struct256", "Struct4k","Struct32k", 
# "PointCloud512k", "PointCloud1m", "PointCloud2m","PointCloud4m", 
# "Range", "NavSatFix", "RadarDetection", "RadarTrack"
#"Array1k", "Array4k", "Array16k", "Array32k", "Array64k", "Array256k","Array1m", "Array2m","Struct256", "Struct4k","Struct32k"
# "RadarDetection","Range", "NavSatFix",  "RadarTrack","PointCloud512k", "PointCloud1m", "PointCloud2m","PointCloud4m"
